# site settings
title: Benny Freeland
subtitle: 
email: ben.freeland16@gmail.com
description: Skier, traveler, drone pilot
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 4000 Mayflower Hill Dr.
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  Telegram: https://telegram.com # https://t.me/mytelegramusername
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram: https://www.instagram.com/bfreebird97
  Youtube: https://www.youtube.com/user/btfree20/
  LinkedIn: https://www.linkedin.com/in/ben-freeland-51327a140/
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

permalink: /blog/:title/

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
